### PR TITLE
grpc for ContainerLogs

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: Yao Zengzeng yaozengzeng@zju.edu.cn

### CODE REVIEW

**Comment by resouer** [comment]
@YaoZengzeng This commit is very clean. But there seems a small bug here:

```
kubectl logs -f busybox

hello world

hello world

hello world

hello world

hello world

hello world

hello world

hello world

hello world

hello world

hello world

hello world
```

Seems every line ends with an extra "enter" ... 

Could you please check the i/o copy part in your implementation?

**Comment by YaoZengzeng** [comment]
There are 8 bytes of prefix in every line of hyperd's log.
Skip it, then everything is fine.

**Comment by resouer** [comment]
> 8 bytes of prefix in every line of hyperd's log

Is this a bug in hyperd? It seems required by hyperd.

[update] Oh, it seems hyperd reused docker's log api, ref: https://github.com/docker/docker/issues/14201

And see:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/
https://medium.com/@dhanushgopinath/reading-docker-container-logs-with-golang-docker-engine-api-702233fac044#.j7upha54i

**Comment by resouer** [comment]
lgtm

**Pull request merged**
