### PR TITLE
Use RFC3339 for time parse

### PR DESCRIPTION
**Pull request by resouer**
hyperd now use RFC3339 for time parse everywhere, we need to keep consistency.

Will send a patch to private after this.

### CODE REVIEW

**Comment by feiskyer** [comment]
@resouer Any reference when hyperd changed this?

**Comment by resouer** [comment]
@feiskyer I believe it's after this commit: https://github.com/hyperhq/hyperd/commit/9f32482a9b283e50c5632258482311f9faf74016 , when `created, err := utils.ParseTimeString(info.Created)` is removed, and then no `utils.ParseTimeString` is used anymore.

**Comment by feiskyer** [comment]
@resouer Got it. LGTM. Could you fix ci first?

**Review by feiskyer — APPROVED** [review]

**Comment by resouer** [comment]
Yes, I'm looking into it

**Pull request merged**
