### PR TITLE
grpc for exec

### PR DESCRIPTION
**Pull request by YaoZengzeng**
not consider GetExitCode temporarily

Signed-off-by: Yao Zengzeng yaozengzeng@zju.edu.cn

### CODE REVIEW

**Comment by feiskyer** [comment]
Same with attach. It's better to pass the attach error message (except of io.EOF) out of goroutines and return the error.

**Comment by resouer** [comment]
This patch is really a good job! Except that `exit` is broken. Will merge this once fixed.

```
$ kubectl exec -it busybox -- /bin/sh
# ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
# exit
error: error executing remote command: error executing command in container: rpc error: code = 1 desc = "context canceled"
```

**Comment by YaoZengzeng** [comment]
After the execution of "exit", the output will end and stream will be cloesd, but input is still blocked for reading from stdin.When it get some input and put it into closed stream,the bug showed above will come up.

Indeed, when we get error  either from input or output,we could return.Otherwise we would get  error unneeded.

**Comment by resouer** [comment]
lgtm

**Pull request merged**
